### ISSUE TITLE
Bug: does not work when multiple lines are selected

### ISSUE THREAD

**Issue by axefrog** [lafe/ContextualDuplicate#1]
Great extension! It had been annoying me that the default line duplication behaviour does not do inline duplicate like Sublime Text does, and your extension worked perfectly in that regard... until I tried to duplicate several selected lines, and it only duplicated one of them and then messed up the resulting selection.

![vscode-contextual-duplicate-bug](https://cloud.githubusercontent.com/assets/298883/17267747/8ed4382c-5654-11e6-942c-ec0526ac229e.gif)

**Comment by lafe** [comment]
Issue should be fixed in version 0.2.0. The main issue was that the selection was messed up and hopefully this is much more robust now.
